# This is the Build docker-compose.yml file. You can build and Run ChurchCRM
# from this file by first filling in your password and db info in the .env
# file and then running "docker-compose build", "docker-compose up" in terminal.

version: "3.6"

services:
  database: #Name of DB Host
    container_name: database
    image: mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - churchcrm-db:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    env_file:
      - .env
    restart: always

  churchcrm:
    container_name: churchcrm
    build: ./
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - database
      - redis
    restart: always
    volumes:
      - churchcrm-files:/var/www/html

volumes:
  churchcrm-files:
    driver: local
  churchcrm-db:
    driver: local